export  {default as NavBar}  from "./NavBar/NavBar";
export  {default as Home}  from "./HomePage/Home/Home";
export  { default as Cart }  from "./Cart/Cart";
export {default as ContextProvider } from "./Context/ContextProvider";
export { default as Generics } from "./Generics/Generics";
export {default as Contact } from "./Contact/Contact";
export {default as MenProduct }  from "./MenProduct/MenProduct";
export { default as Women } from "./Women/Women";
export {default as Accessories } from "./Accessories/Accessories";
export { default as Mobile } from "./Mobile/Mobile";
export { default as ProductDetails } from "./ProductDetails/ProductDetails";
export { default as SingIn } from "./Authentication/SingIn";